# Generated by Django 3.1.7 on 2021-02-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cw1app', '0002_auto_20210221_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='id',
            new_name='key',
        ),
    ]
